### ISSUE TITLE
panics are hard to debug

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/datadriven#30]
If a test panics, it is very hard to find which one it is. @mgartner ran into this as well.

In verbose mode, we `Logf` each testcase but that doesn't get printed to the output immediately, and it is not shown if we panic. Replacing it with `fmt.Printf` works. I'm not sure if we should do that or maybe add the Printf and also keep the Logf? CC @knz

**Comment by knz** [comment]
go 1.14 should ensure that Logf output is emitted immediately so it remains upon panic.

(This was a 1.13 bug fixed in 1.14. Are you guys still running tests with 1.13?)

**Comment by RaduBerinde** [comment]
Ah, yeah, Cockroach reverted to using 1.13 because of an issue and will skip directly to 1.15.

**Comment by knz** [comment]
I think in the meantime you can run your testing with 1.14. Even if we don't release binaries with it the crdb runs fine.
