### ISSUE TITLE
Re-consider running each directive in its own sub-test

### ISSUE THREAD

**Issue by knz** [cockroachdb/datadriven#8]
Discussed offline with @RaduBerinde: running each-directive in its own sub-test has two drawbacks:

- it triggers the sub-test machinery inside Go's `testing` package, which has some time overhead

- it causes extra log lines _per directive_ when running with `-v` (the default with crdb's CI)

@RaduBerinde reports that at least one `sql/opt` test duration goes from 1.4s to 2.5s as a result.

Questions:

- what requirement is satisfied by running each directive in its own sub-test? (i.e. what was the motivation for commit 5fd2960cd810d24290d80d367b4c0f1166ae15c2?)

- is there a way to satisfy that requirement without a sub-test?

**Comment by knz** [comment]
@tbg can you perhaps chime in about the motivation for the linked commit 5fd2960cd810d24290d80d367b4c0f1166ae15c2? thx

**Comment by RaduBerinde** [comment]
See more specific info in #9.

**Comment by tbg** [comment]
Let's rip it out, sorry for the inconvenience. There wasn't a strong motivation for introducing this other than it seeming useful at the time, which it turns out it isn't.

**Comment by knz** [comment]
It's OK. I'm going to tweak the code to introduce sub-test *sections* like we have in the SQL logic tests. That's going to make it possible to collate multiple tests inside the same file so that they can be individually filtered out.

**Comment by RaduBerinde** [comment]
Just my 2c but I am not crazy about the subtest sections in their current form either. You end up unwittingly adding more tests to the last (unrelated) subtest, and you very rarely check that a subtest doesn't depend on stuff in previous subtests. I would rather allow splitting in files, eg using a special delimiter (eg test1--subtest1, test1--subtest2) and have the framework treat them all as a single test.

**Comment by knz** [comment]
I was thinking about having both start and end markers for subtests, what do you think?

Can you also give an example of your proposal, I don't fully understand it.

**Comment by RaduBerinde** [comment]
Yeah I had that thought too after writing the previous comment, I think end markers would help! Especially if they are not optional so they are always there, even for the last subtest.

My example was that we could have files `testdata/fk--insert`, `testdata/fk--update`, `testdata/fk--whatever` and these are all put in a single `fk` test with various subtests. The only real difference between this and just separating them into completely different tests is that we don't reinitialize between them. But it's pretty janky, maybe the best thing would be to provide more helpers to allow subdirectories, so you'd have `testdata/fk/insert`, `testdata/fk/update` and the subtests would follow the structure of the tree, with initialization running once per subdirectory. I guess the optimizer kind of does something like this already, we have multiple subdirectories and each one corresponds to a different `TestXXX` (see `opt/memo/memo_test.go`).

**Comment by knz** [comment]
> the best thing would be to provide more helpers to allow subdirectories, so you'd have testdata/fk/insert, testdata/fk/update and the subtests would follow the structure of the tree

This is already the case today. Technically, the sub-tests are ran side-by-side for all the sub-directories (i.e. not in a parent-child relationship) but this is immaterial to `go test`: the test _names_ are generated in the same way, and the filtering/selection process applies regular expressions in the same way to both approaches.

The idea of sub-tests would add just one extra layer to enable sub-test within a single input file. That would always be the last component in the test name.
